/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudwick.generator.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CustomerRating extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerRating\",\"namespace\":\"com.cloudwick.generator.avro\",\"fields\":[{\"name\":\"CId\",\"type\":\"int\"},{\"name\":\"MovieID\",\"type\":\"string\"},{\"name\":\"MovieName\",\"type\":\"string\"},{\"name\":\"CName\",\"type\":\"string\"},{\"name\":\"MovieRating\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int CId;
  @Deprecated public java.lang.CharSequence MovieID;
  @Deprecated public java.lang.CharSequence MovieName;
  @Deprecated public java.lang.CharSequence CName;
  @Deprecated public java.lang.CharSequence MovieRating;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CustomerRating() {}

  /**
   * All-args constructor.
   */
  public CustomerRating(java.lang.Integer CId, java.lang.CharSequence MovieID, java.lang.CharSequence MovieName, java.lang.CharSequence CName, java.lang.CharSequence MovieRating) {
    this.CId = CId;
    this.MovieID = MovieID;
    this.MovieName = MovieName;
    this.CName = CName;
    this.MovieRating = MovieRating;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CId;
    case 1: return MovieID;
    case 2: return MovieName;
    case 3: return CName;
    case 4: return MovieRating;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CId = (java.lang.Integer)value$; break;
    case 1: MovieID = (java.lang.CharSequence)value$; break;
    case 2: MovieName = (java.lang.CharSequence)value$; break;
    case 3: CName = (java.lang.CharSequence)value$; break;
    case 4: MovieRating = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CId' field.
   */
  public java.lang.Integer getCId() {
    return CId;
  }

  /**
   * Sets the value of the 'CId' field.
   * @param value the value to set.
   */
  public void setCId(java.lang.Integer value) {
    this.CId = value;
  }

  /**
   * Gets the value of the 'MovieID' field.
   */
  public java.lang.CharSequence getMovieID() {
    return MovieID;
  }

  /**
   * Sets the value of the 'MovieID' field.
   * @param value the value to set.
   */
  public void setMovieID(java.lang.CharSequence value) {
    this.MovieID = value;
  }

  /**
   * Gets the value of the 'MovieName' field.
   */
  public java.lang.CharSequence getMovieName() {
    return MovieName;
  }

  /**
   * Sets the value of the 'MovieName' field.
   * @param value the value to set.
   */
  public void setMovieName(java.lang.CharSequence value) {
    this.MovieName = value;
  }

  /**
   * Gets the value of the 'CName' field.
   */
  public java.lang.CharSequence getCName() {
    return CName;
  }

  /**
   * Sets the value of the 'CName' field.
   * @param value the value to set.
   */
  public void setCName(java.lang.CharSequence value) {
    this.CName = value;
  }

  /**
   * Gets the value of the 'MovieRating' field.
   */
  public java.lang.CharSequence getMovieRating() {
    return MovieRating;
  }

  /**
   * Sets the value of the 'MovieRating' field.
   * @param value the value to set.
   */
  public void setMovieRating(java.lang.CharSequence value) {
    this.MovieRating = value;
  }

  /** Creates a new CustomerRating RecordBuilder */
  public static com.cloudwick.generator.avro.CustomerRating.Builder newBuilder() {
    return new com.cloudwick.generator.avro.CustomerRating.Builder();
  }
  
  /** Creates a new CustomerRating RecordBuilder by copying an existing Builder */
  public static com.cloudwick.generator.avro.CustomerRating.Builder newBuilder(com.cloudwick.generator.avro.CustomerRating.Builder other) {
    return new com.cloudwick.generator.avro.CustomerRating.Builder(other);
  }
  
  /** Creates a new CustomerRating RecordBuilder by copying an existing CustomerRating instance */
  public static com.cloudwick.generator.avro.CustomerRating.Builder newBuilder(com.cloudwick.generator.avro.CustomerRating other) {
    return new com.cloudwick.generator.avro.CustomerRating.Builder(other);
  }
  
  /**
   * RecordBuilder for CustomerRating instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerRating>
    implements org.apache.avro.data.RecordBuilder<CustomerRating> {

    private int CId;
    private java.lang.CharSequence MovieID;
    private java.lang.CharSequence MovieName;
    private java.lang.CharSequence CName;
    private java.lang.CharSequence MovieRating;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudwick.generator.avro.CustomerRating.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudwick.generator.avro.CustomerRating.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MovieID)) {
        this.MovieID = data().deepCopy(fields()[1].schema(), other.MovieID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MovieName)) {
        this.MovieName = data().deepCopy(fields()[2].schema(), other.MovieName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CName)) {
        this.CName = data().deepCopy(fields()[3].schema(), other.CName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.MovieRating)) {
        this.MovieRating = data().deepCopy(fields()[4].schema(), other.MovieRating);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CustomerRating instance */
    private Builder(com.cloudwick.generator.avro.CustomerRating other) {
            super(com.cloudwick.generator.avro.CustomerRating.SCHEMA$);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MovieID)) {
        this.MovieID = data().deepCopy(fields()[1].schema(), other.MovieID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MovieName)) {
        this.MovieName = data().deepCopy(fields()[2].schema(), other.MovieName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CName)) {
        this.CName = data().deepCopy(fields()[3].schema(), other.CName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.MovieRating)) {
        this.MovieRating = data().deepCopy(fields()[4].schema(), other.MovieRating);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'CId' field */
    public java.lang.Integer getCId() {
      return CId;
    }
    
    /** Sets the value of the 'CId' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder setCId(int value) {
      validate(fields()[0], value);
      this.CId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'CId' field has been set */
    public boolean hasCId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'CId' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder clearCId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'MovieID' field */
    public java.lang.CharSequence getMovieID() {
      return MovieID;
    }
    
    /** Sets the value of the 'MovieID' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder setMovieID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.MovieID = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieID' field has been set */
    public boolean hasMovieID() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'MovieID' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder clearMovieID() {
      MovieID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'MovieName' field */
    public java.lang.CharSequence getMovieName() {
      return MovieName;
    }
    
    /** Sets the value of the 'MovieName' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder setMovieName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.MovieName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieName' field has been set */
    public boolean hasMovieName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'MovieName' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder clearMovieName() {
      MovieName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'CName' field */
    public java.lang.CharSequence getCName() {
      return CName;
    }
    
    /** Sets the value of the 'CName' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder setCName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.CName = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'CName' field has been set */
    public boolean hasCName() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'CName' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder clearCName() {
      CName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'MovieRating' field */
    public java.lang.CharSequence getMovieRating() {
      return MovieRating;
    }
    
    /** Sets the value of the 'MovieRating' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder setMovieRating(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.MovieRating = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieRating' field has been set */
    public boolean hasMovieRating() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'MovieRating' field */
    public com.cloudwick.generator.avro.CustomerRating.Builder clearMovieRating() {
      MovieRating = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public CustomerRating build() {
      try {
        CustomerRating record = new CustomerRating();
        record.CId = fieldSetFlags()[0] ? this.CId : (java.lang.Integer) defaultValue(fields()[0]);
        record.MovieID = fieldSetFlags()[1] ? this.MovieID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.MovieName = fieldSetFlags()[2] ? this.MovieName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CName = fieldSetFlags()[3] ? this.CName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.MovieRating = fieldSetFlags()[4] ? this.MovieRating : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
