/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudwick.generator.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Fact extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Fact\",\"namespace\":\"com.cloudwick.generator.avro\",\"fields\":[{\"name\":\"CId\",\"type\":\"string\"},{\"name\":\"CGamePlayed\",\"type\":\"string\"},{\"name\":\"CGamePlayedDate\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence CId;
  @Deprecated public java.lang.CharSequence CGamePlayed;
  @Deprecated public long CGamePlayedDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Fact() {}

  /**
   * All-args constructor.
   */
  public Fact(java.lang.CharSequence CId, java.lang.CharSequence CGamePlayed, java.lang.Long CGamePlayedDate) {
    this.CId = CId;
    this.CGamePlayed = CGamePlayed;
    this.CGamePlayedDate = CGamePlayedDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CId;
    case 1: return CGamePlayed;
    case 2: return CGamePlayedDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CId = (java.lang.CharSequence)value$; break;
    case 1: CGamePlayed = (java.lang.CharSequence)value$; break;
    case 2: CGamePlayedDate = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CId' field.
   */
  public java.lang.CharSequence getCId() {
    return CId;
  }

  /**
   * Sets the value of the 'CId' field.
   * @param value the value to set.
   */
  public void setCId(java.lang.CharSequence value) {
    this.CId = value;
  }

  /**
   * Gets the value of the 'CGamePlayed' field.
   */
  public java.lang.CharSequence getCGamePlayed() {
    return CGamePlayed;
  }

  /**
   * Sets the value of the 'CGamePlayed' field.
   * @param value the value to set.
   */
  public void setCGamePlayed(java.lang.CharSequence value) {
    this.CGamePlayed = value;
  }

  /**
   * Gets the value of the 'CGamePlayedDate' field.
   */
  public java.lang.Long getCGamePlayedDate() {
    return CGamePlayedDate;
  }

  /**
   * Sets the value of the 'CGamePlayedDate' field.
   * @param value the value to set.
   */
  public void setCGamePlayedDate(java.lang.Long value) {
    this.CGamePlayedDate = value;
  }

  /** Creates a new Fact RecordBuilder */
  public static com.cloudwick.generator.avro.Fact.Builder newBuilder() {
    return new com.cloudwick.generator.avro.Fact.Builder();
  }
  
  /** Creates a new Fact RecordBuilder by copying an existing Builder */
  public static com.cloudwick.generator.avro.Fact.Builder newBuilder(com.cloudwick.generator.avro.Fact.Builder other) {
    return new com.cloudwick.generator.avro.Fact.Builder(other);
  }
  
  /** Creates a new Fact RecordBuilder by copying an existing Fact instance */
  public static com.cloudwick.generator.avro.Fact.Builder newBuilder(com.cloudwick.generator.avro.Fact other) {
    return new com.cloudwick.generator.avro.Fact.Builder(other);
  }
  
  /**
   * RecordBuilder for Fact instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Fact>
    implements org.apache.avro.data.RecordBuilder<Fact> {

    private java.lang.CharSequence CId;
    private java.lang.CharSequence CGamePlayed;
    private long CGamePlayedDate;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudwick.generator.avro.Fact.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudwick.generator.avro.Fact.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CGamePlayed)) {
        this.CGamePlayed = data().deepCopy(fields()[1].schema(), other.CGamePlayed);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CGamePlayedDate)) {
        this.CGamePlayedDate = data().deepCopy(fields()[2].schema(), other.CGamePlayedDate);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Fact instance */
    private Builder(com.cloudwick.generator.avro.Fact other) {
            super(com.cloudwick.generator.avro.Fact.SCHEMA$);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CGamePlayed)) {
        this.CGamePlayed = data().deepCopy(fields()[1].schema(), other.CGamePlayed);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CGamePlayedDate)) {
        this.CGamePlayedDate = data().deepCopy(fields()[2].schema(), other.CGamePlayedDate);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'CId' field */
    public java.lang.CharSequence getCId() {
      return CId;
    }
    
    /** Sets the value of the 'CId' field */
    public com.cloudwick.generator.avro.Fact.Builder setCId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'CId' field has been set */
    public boolean hasCId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'CId' field */
    public com.cloudwick.generator.avro.Fact.Builder clearCId() {
      CId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'CGamePlayed' field */
    public java.lang.CharSequence getCGamePlayed() {
      return CGamePlayed;
    }
    
    /** Sets the value of the 'CGamePlayed' field */
    public com.cloudwick.generator.avro.Fact.Builder setCGamePlayed(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CGamePlayed = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'CGamePlayed' field has been set */
    public boolean hasCGamePlayed() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'CGamePlayed' field */
    public com.cloudwick.generator.avro.Fact.Builder clearCGamePlayed() {
      CGamePlayed = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'CGamePlayedDate' field */
    public java.lang.Long getCGamePlayedDate() {
      return CGamePlayedDate;
    }
    
    /** Sets the value of the 'CGamePlayedDate' field */
    public com.cloudwick.generator.avro.Fact.Builder setCGamePlayedDate(long value) {
      validate(fields()[2], value);
      this.CGamePlayedDate = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'CGamePlayedDate' field has been set */
    public boolean hasCGamePlayedDate() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'CGamePlayedDate' field */
    public com.cloudwick.generator.avro.Fact.Builder clearCGamePlayedDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Fact build() {
      try {
        Fact record = new Fact();
        record.CId = fieldSetFlags()[0] ? this.CId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CGamePlayed = fieldSetFlags()[1] ? this.CGamePlayed : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.CGamePlayedDate = fieldSetFlags()[2] ? this.CGamePlayedDate : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
