/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudwick.generator.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MovieGenre extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MovieGenre\",\"namespace\":\"com.cloudwick.generator.avro\",\"fields\":[{\"name\":\"MovieGenre\",\"type\":\"string\"},{\"name\":\"MovieReleaseDate\",\"type\":\"string\"},{\"name\":\"MovieID\",\"type\":\"string\"},{\"name\":\"MovieLength\",\"type\":\"int\"},{\"name\":\"MovieName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence MovieGenre;
  @Deprecated public java.lang.CharSequence MovieReleaseDate;
  @Deprecated public java.lang.CharSequence MovieID;
  @Deprecated public int MovieLength;
  @Deprecated public java.lang.CharSequence MovieName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public MovieGenre() {}

  /**
   * All-args constructor.
   */
  public MovieGenre(java.lang.CharSequence MovieGenre, java.lang.CharSequence MovieReleaseDate, java.lang.CharSequence MovieID, java.lang.Integer MovieLength, java.lang.CharSequence MovieName) {
    this.MovieGenre = MovieGenre;
    this.MovieReleaseDate = MovieReleaseDate;
    this.MovieID = MovieID;
    this.MovieLength = MovieLength;
    this.MovieName = MovieName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return MovieGenre;
    case 1: return MovieReleaseDate;
    case 2: return MovieID;
    case 3: return MovieLength;
    case 4: return MovieName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: MovieGenre = (java.lang.CharSequence)value$; break;
    case 1: MovieReleaseDate = (java.lang.CharSequence)value$; break;
    case 2: MovieID = (java.lang.CharSequence)value$; break;
    case 3: MovieLength = (java.lang.Integer)value$; break;
    case 4: MovieName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'MovieGenre' field.
   */
  public java.lang.CharSequence getMovieGenre() {
    return MovieGenre;
  }

  /**
   * Sets the value of the 'MovieGenre' field.
   * @param value the value to set.
   */
  public void setMovieGenre(java.lang.CharSequence value) {
    this.MovieGenre = value;
  }

  /**
   * Gets the value of the 'MovieReleaseDate' field.
   */
  public java.lang.CharSequence getMovieReleaseDate() {
    return MovieReleaseDate;
  }

  /**
   * Sets the value of the 'MovieReleaseDate' field.
   * @param value the value to set.
   */
  public void setMovieReleaseDate(java.lang.CharSequence value) {
    this.MovieReleaseDate = value;
  }

  /**
   * Gets the value of the 'MovieID' field.
   */
  public java.lang.CharSequence getMovieID() {
    return MovieID;
  }

  /**
   * Sets the value of the 'MovieID' field.
   * @param value the value to set.
   */
  public void setMovieID(java.lang.CharSequence value) {
    this.MovieID = value;
  }

  /**
   * Gets the value of the 'MovieLength' field.
   */
  public java.lang.Integer getMovieLength() {
    return MovieLength;
  }

  /**
   * Sets the value of the 'MovieLength' field.
   * @param value the value to set.
   */
  public void setMovieLength(java.lang.Integer value) {
    this.MovieLength = value;
  }

  /**
   * Gets the value of the 'MovieName' field.
   */
  public java.lang.CharSequence getMovieName() {
    return MovieName;
  }

  /**
   * Sets the value of the 'MovieName' field.
   * @param value the value to set.
   */
  public void setMovieName(java.lang.CharSequence value) {
    this.MovieName = value;
  }

  /** Creates a new MovieGenre RecordBuilder */
  public static com.cloudwick.generator.avro.MovieGenre.Builder newBuilder() {
    return new com.cloudwick.generator.avro.MovieGenre.Builder();
  }
  
  /** Creates a new MovieGenre RecordBuilder by copying an existing Builder */
  public static com.cloudwick.generator.avro.MovieGenre.Builder newBuilder(com.cloudwick.generator.avro.MovieGenre.Builder other) {
    return new com.cloudwick.generator.avro.MovieGenre.Builder(other);
  }
  
  /** Creates a new MovieGenre RecordBuilder by copying an existing MovieGenre instance */
  public static com.cloudwick.generator.avro.MovieGenre.Builder newBuilder(com.cloudwick.generator.avro.MovieGenre other) {
    return new com.cloudwick.generator.avro.MovieGenre.Builder(other);
  }
  
  /**
   * RecordBuilder for MovieGenre instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MovieGenre>
    implements org.apache.avro.data.RecordBuilder<MovieGenre> {

    private java.lang.CharSequence MovieGenre;
    private java.lang.CharSequence MovieReleaseDate;
    private java.lang.CharSequence MovieID;
    private int MovieLength;
    private java.lang.CharSequence MovieName;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudwick.generator.avro.MovieGenre.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudwick.generator.avro.MovieGenre.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.MovieGenre)) {
        this.MovieGenre = data().deepCopy(fields()[0].schema(), other.MovieGenre);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MovieReleaseDate)) {
        this.MovieReleaseDate = data().deepCopy(fields()[1].schema(), other.MovieReleaseDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MovieID)) {
        this.MovieID = data().deepCopy(fields()[2].schema(), other.MovieID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.MovieLength)) {
        this.MovieLength = data().deepCopy(fields()[3].schema(), other.MovieLength);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.MovieName)) {
        this.MovieName = data().deepCopy(fields()[4].schema(), other.MovieName);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing MovieGenre instance */
    private Builder(com.cloudwick.generator.avro.MovieGenre other) {
            super(com.cloudwick.generator.avro.MovieGenre.SCHEMA$);
      if (isValidValue(fields()[0], other.MovieGenre)) {
        this.MovieGenre = data().deepCopy(fields()[0].schema(), other.MovieGenre);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MovieReleaseDate)) {
        this.MovieReleaseDate = data().deepCopy(fields()[1].schema(), other.MovieReleaseDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MovieID)) {
        this.MovieID = data().deepCopy(fields()[2].schema(), other.MovieID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.MovieLength)) {
        this.MovieLength = data().deepCopy(fields()[3].schema(), other.MovieLength);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.MovieName)) {
        this.MovieName = data().deepCopy(fields()[4].schema(), other.MovieName);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'MovieGenre' field */
    public java.lang.CharSequence getMovieGenre() {
      return MovieGenre;
    }
    
    /** Sets the value of the 'MovieGenre' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder setMovieGenre(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.MovieGenre = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieGenre' field has been set */
    public boolean hasMovieGenre() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'MovieGenre' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder clearMovieGenre() {
      MovieGenre = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'MovieReleaseDate' field */
    public java.lang.CharSequence getMovieReleaseDate() {
      return MovieReleaseDate;
    }
    
    /** Sets the value of the 'MovieReleaseDate' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder setMovieReleaseDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.MovieReleaseDate = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieReleaseDate' field has been set */
    public boolean hasMovieReleaseDate() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'MovieReleaseDate' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder clearMovieReleaseDate() {
      MovieReleaseDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'MovieID' field */
    public java.lang.CharSequence getMovieID() {
      return MovieID;
    }
    
    /** Sets the value of the 'MovieID' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder setMovieID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.MovieID = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieID' field has been set */
    public boolean hasMovieID() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'MovieID' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder clearMovieID() {
      MovieID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'MovieLength' field */
    public java.lang.Integer getMovieLength() {
      return MovieLength;
    }
    
    /** Sets the value of the 'MovieLength' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder setMovieLength(int value) {
      validate(fields()[3], value);
      this.MovieLength = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieLength' field has been set */
    public boolean hasMovieLength() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'MovieLength' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder clearMovieLength() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'MovieName' field */
    public java.lang.CharSequence getMovieName() {
      return MovieName;
    }
    
    /** Sets the value of the 'MovieName' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder setMovieName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.MovieName = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieName' field has been set */
    public boolean hasMovieName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'MovieName' field */
    public com.cloudwick.generator.avro.MovieGenre.Builder clearMovieName() {
      MovieName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public MovieGenre build() {
      try {
        MovieGenre record = new MovieGenre();
        record.MovieGenre = fieldSetFlags()[0] ? this.MovieGenre : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.MovieReleaseDate = fieldSetFlags()[1] ? this.MovieReleaseDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.MovieID = fieldSetFlags()[2] ? this.MovieID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.MovieLength = fieldSetFlags()[3] ? this.MovieLength : (java.lang.Integer) defaultValue(fields()[3]);
        record.MovieName = fieldSetFlags()[4] ? this.MovieName : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
