/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudwick.generator.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ODVSRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ODVSRecord\",\"namespace\":\"com.cloudwick.generator.avro\",\"fields\":[{\"name\":\"CId\",\"type\":\"int\"},{\"name\":\"CName\",\"type\":\"string\"},{\"name\":\"UserActive\",\"type\":\"int\"},{\"name\":\"TimeStamp\",\"type\":\"long\"},{\"name\":\"PauseTime\",\"type\":\"long\"},{\"name\":\"MovieRating\",\"type\":\"string\"},{\"name\":\"MovieID\",\"type\":\"string\"},{\"name\":\"MovieName\",\"type\":\"string\"},{\"name\":\"MovieReleaseDate\",\"type\":\"string\"},{\"name\":\"MovieLength\",\"type\":\"int\"},{\"name\":\"MovieGenre\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int CId;
  @Deprecated public java.lang.CharSequence CName;
  @Deprecated public int UserActive;
  @Deprecated public long TimeStamp;
  @Deprecated public long PauseTime;
  @Deprecated public java.lang.CharSequence MovieRating;
  @Deprecated public java.lang.CharSequence MovieID;
  @Deprecated public java.lang.CharSequence MovieName;
  @Deprecated public java.lang.CharSequence MovieReleaseDate;
  @Deprecated public int MovieLength;
  @Deprecated public java.lang.CharSequence MovieGenre;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ODVSRecord() {}

  /**
   * All-args constructor.
   */
  public ODVSRecord(java.lang.Integer CId, java.lang.CharSequence CName, java.lang.Integer UserActive, java.lang.Long TimeStamp, java.lang.Long PauseTime, java.lang.CharSequence MovieRating, java.lang.CharSequence MovieID, java.lang.CharSequence MovieName, java.lang.CharSequence MovieReleaseDate, java.lang.Integer MovieLength, java.lang.CharSequence MovieGenre) {
    this.CId = CId;
    this.CName = CName;
    this.UserActive = UserActive;
    this.TimeStamp = TimeStamp;
    this.PauseTime = PauseTime;
    this.MovieRating = MovieRating;
    this.MovieID = MovieID;
    this.MovieName = MovieName;
    this.MovieReleaseDate = MovieReleaseDate;
    this.MovieLength = MovieLength;
    this.MovieGenre = MovieGenre;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CId;
    case 1: return CName;
    case 2: return UserActive;
    case 3: return TimeStamp;
    case 4: return PauseTime;
    case 5: return MovieRating;
    case 6: return MovieID;
    case 7: return MovieName;
    case 8: return MovieReleaseDate;
    case 9: return MovieLength;
    case 10: return MovieGenre;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CId = (java.lang.Integer)value$; break;
    case 1: CName = (java.lang.CharSequence)value$; break;
    case 2: UserActive = (java.lang.Integer)value$; break;
    case 3: TimeStamp = (java.lang.Long)value$; break;
    case 4: PauseTime = (java.lang.Long)value$; break;
    case 5: MovieRating = (java.lang.CharSequence)value$; break;
    case 6: MovieID = (java.lang.CharSequence)value$; break;
    case 7: MovieName = (java.lang.CharSequence)value$; break;
    case 8: MovieReleaseDate = (java.lang.CharSequence)value$; break;
    case 9: MovieLength = (java.lang.Integer)value$; break;
    case 10: MovieGenre = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CId' field.
   */
  public java.lang.Integer getCId() {
    return CId;
  }

  /**
   * Sets the value of the 'CId' field.
   * @param value the value to set.
   */
  public void setCId(java.lang.Integer value) {
    this.CId = value;
  }

  /**
   * Gets the value of the 'CName' field.
   */
  public java.lang.CharSequence getCName() {
    return CName;
  }

  /**
   * Sets the value of the 'CName' field.
   * @param value the value to set.
   */
  public void setCName(java.lang.CharSequence value) {
    this.CName = value;
  }

  /**
   * Gets the value of the 'UserActive' field.
   */
  public java.lang.Integer getUserActive() {
    return UserActive;
  }

  /**
   * Sets the value of the 'UserActive' field.
   * @param value the value to set.
   */
  public void setUserActive(java.lang.Integer value) {
    this.UserActive = value;
  }

  /**
   * Gets the value of the 'TimeStamp' field.
   */
  public java.lang.Long getTimeStamp() {
    return TimeStamp;
  }

  /**
   * Sets the value of the 'TimeStamp' field.
   * @param value the value to set.
   */
  public void setTimeStamp(java.lang.Long value) {
    this.TimeStamp = value;
  }

  /**
   * Gets the value of the 'PauseTime' field.
   */
  public java.lang.Long getPauseTime() {
    return PauseTime;
  }

  /**
   * Sets the value of the 'PauseTime' field.
   * @param value the value to set.
   */
  public void setPauseTime(java.lang.Long value) {
    this.PauseTime = value;
  }

  /**
   * Gets the value of the 'MovieRating' field.
   */
  public java.lang.CharSequence getMovieRating() {
    return MovieRating;
  }

  /**
   * Sets the value of the 'MovieRating' field.
   * @param value the value to set.
   */
  public void setMovieRating(java.lang.CharSequence value) {
    this.MovieRating = value;
  }

  /**
   * Gets the value of the 'MovieID' field.
   */
  public java.lang.CharSequence getMovieID() {
    return MovieID;
  }

  /**
   * Sets the value of the 'MovieID' field.
   * @param value the value to set.
   */
  public void setMovieID(java.lang.CharSequence value) {
    this.MovieID = value;
  }

  /**
   * Gets the value of the 'MovieName' field.
   */
  public java.lang.CharSequence getMovieName() {
    return MovieName;
  }

  /**
   * Sets the value of the 'MovieName' field.
   * @param value the value to set.
   */
  public void setMovieName(java.lang.CharSequence value) {
    this.MovieName = value;
  }

  /**
   * Gets the value of the 'MovieReleaseDate' field.
   */
  public java.lang.CharSequence getMovieReleaseDate() {
    return MovieReleaseDate;
  }

  /**
   * Sets the value of the 'MovieReleaseDate' field.
   * @param value the value to set.
   */
  public void setMovieReleaseDate(java.lang.CharSequence value) {
    this.MovieReleaseDate = value;
  }

  /**
   * Gets the value of the 'MovieLength' field.
   */
  public java.lang.Integer getMovieLength() {
    return MovieLength;
  }

  /**
   * Sets the value of the 'MovieLength' field.
   * @param value the value to set.
   */
  public void setMovieLength(java.lang.Integer value) {
    this.MovieLength = value;
  }

  /**
   * Gets the value of the 'MovieGenre' field.
   */
  public java.lang.CharSequence getMovieGenre() {
    return MovieGenre;
  }

  /**
   * Sets the value of the 'MovieGenre' field.
   * @param value the value to set.
   */
  public void setMovieGenre(java.lang.CharSequence value) {
    this.MovieGenre = value;
  }

  /** Creates a new ODVSRecord RecordBuilder */
  public static com.cloudwick.generator.avro.ODVSRecord.Builder newBuilder() {
    return new com.cloudwick.generator.avro.ODVSRecord.Builder();
  }
  
  /** Creates a new ODVSRecord RecordBuilder by copying an existing Builder */
  public static com.cloudwick.generator.avro.ODVSRecord.Builder newBuilder(com.cloudwick.generator.avro.ODVSRecord.Builder other) {
    return new com.cloudwick.generator.avro.ODVSRecord.Builder(other);
  }
  
  /** Creates a new ODVSRecord RecordBuilder by copying an existing ODVSRecord instance */
  public static com.cloudwick.generator.avro.ODVSRecord.Builder newBuilder(com.cloudwick.generator.avro.ODVSRecord other) {
    return new com.cloudwick.generator.avro.ODVSRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for ODVSRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ODVSRecord>
    implements org.apache.avro.data.RecordBuilder<ODVSRecord> {

    private int CId;
    private java.lang.CharSequence CName;
    private int UserActive;
    private long TimeStamp;
    private long PauseTime;
    private java.lang.CharSequence MovieRating;
    private java.lang.CharSequence MovieID;
    private java.lang.CharSequence MovieName;
    private java.lang.CharSequence MovieReleaseDate;
    private int MovieLength;
    private java.lang.CharSequence MovieGenre;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudwick.generator.avro.ODVSRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudwick.generator.avro.ODVSRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CName)) {
        this.CName = data().deepCopy(fields()[1].schema(), other.CName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UserActive)) {
        this.UserActive = data().deepCopy(fields()[2].schema(), other.UserActive);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.TimeStamp)) {
        this.TimeStamp = data().deepCopy(fields()[3].schema(), other.TimeStamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.PauseTime)) {
        this.PauseTime = data().deepCopy(fields()[4].schema(), other.PauseTime);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.MovieRating)) {
        this.MovieRating = data().deepCopy(fields()[5].schema(), other.MovieRating);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.MovieID)) {
        this.MovieID = data().deepCopy(fields()[6].schema(), other.MovieID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.MovieName)) {
        this.MovieName = data().deepCopy(fields()[7].schema(), other.MovieName);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.MovieReleaseDate)) {
        this.MovieReleaseDate = data().deepCopy(fields()[8].schema(), other.MovieReleaseDate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.MovieLength)) {
        this.MovieLength = data().deepCopy(fields()[9].schema(), other.MovieLength);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.MovieGenre)) {
        this.MovieGenre = data().deepCopy(fields()[10].schema(), other.MovieGenre);
        fieldSetFlags()[10] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ODVSRecord instance */
    private Builder(com.cloudwick.generator.avro.ODVSRecord other) {
            super(com.cloudwick.generator.avro.ODVSRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CName)) {
        this.CName = data().deepCopy(fields()[1].schema(), other.CName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.UserActive)) {
        this.UserActive = data().deepCopy(fields()[2].schema(), other.UserActive);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.TimeStamp)) {
        this.TimeStamp = data().deepCopy(fields()[3].schema(), other.TimeStamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.PauseTime)) {
        this.PauseTime = data().deepCopy(fields()[4].schema(), other.PauseTime);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.MovieRating)) {
        this.MovieRating = data().deepCopy(fields()[5].schema(), other.MovieRating);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.MovieID)) {
        this.MovieID = data().deepCopy(fields()[6].schema(), other.MovieID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.MovieName)) {
        this.MovieName = data().deepCopy(fields()[7].schema(), other.MovieName);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.MovieReleaseDate)) {
        this.MovieReleaseDate = data().deepCopy(fields()[8].schema(), other.MovieReleaseDate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.MovieLength)) {
        this.MovieLength = data().deepCopy(fields()[9].schema(), other.MovieLength);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.MovieGenre)) {
        this.MovieGenre = data().deepCopy(fields()[10].schema(), other.MovieGenre);
        fieldSetFlags()[10] = true;
      }
    }

    /** Gets the value of the 'CId' field */
    public java.lang.Integer getCId() {
      return CId;
    }
    
    /** Sets the value of the 'CId' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setCId(int value) {
      validate(fields()[0], value);
      this.CId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'CId' field has been set */
    public boolean hasCId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'CId' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearCId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'CName' field */
    public java.lang.CharSequence getCName() {
      return CName;
    }
    
    /** Sets the value of the 'CName' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setCName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'CName' field has been set */
    public boolean hasCName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'CName' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearCName() {
      CName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'UserActive' field */
    public java.lang.Integer getUserActive() {
      return UserActive;
    }
    
    /** Sets the value of the 'UserActive' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setUserActive(int value) {
      validate(fields()[2], value);
      this.UserActive = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'UserActive' field has been set */
    public boolean hasUserActive() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'UserActive' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearUserActive() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'TimeStamp' field */
    public java.lang.Long getTimeStamp() {
      return TimeStamp;
    }
    
    /** Sets the value of the 'TimeStamp' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setTimeStamp(long value) {
      validate(fields()[3], value);
      this.TimeStamp = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'TimeStamp' field has been set */
    public boolean hasTimeStamp() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'TimeStamp' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearTimeStamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'PauseTime' field */
    public java.lang.Long getPauseTime() {
      return PauseTime;
    }
    
    /** Sets the value of the 'PauseTime' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setPauseTime(long value) {
      validate(fields()[4], value);
      this.PauseTime = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'PauseTime' field has been set */
    public boolean hasPauseTime() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'PauseTime' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearPauseTime() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'MovieRating' field */
    public java.lang.CharSequence getMovieRating() {
      return MovieRating;
    }
    
    /** Sets the value of the 'MovieRating' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setMovieRating(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.MovieRating = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieRating' field has been set */
    public boolean hasMovieRating() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'MovieRating' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearMovieRating() {
      MovieRating = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'MovieID' field */
    public java.lang.CharSequence getMovieID() {
      return MovieID;
    }
    
    /** Sets the value of the 'MovieID' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setMovieID(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.MovieID = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieID' field has been set */
    public boolean hasMovieID() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'MovieID' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearMovieID() {
      MovieID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'MovieName' field */
    public java.lang.CharSequence getMovieName() {
      return MovieName;
    }
    
    /** Sets the value of the 'MovieName' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setMovieName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.MovieName = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieName' field has been set */
    public boolean hasMovieName() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'MovieName' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearMovieName() {
      MovieName = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'MovieReleaseDate' field */
    public java.lang.CharSequence getMovieReleaseDate() {
      return MovieReleaseDate;
    }
    
    /** Sets the value of the 'MovieReleaseDate' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setMovieReleaseDate(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.MovieReleaseDate = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieReleaseDate' field has been set */
    public boolean hasMovieReleaseDate() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'MovieReleaseDate' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearMovieReleaseDate() {
      MovieReleaseDate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'MovieLength' field */
    public java.lang.Integer getMovieLength() {
      return MovieLength;
    }
    
    /** Sets the value of the 'MovieLength' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setMovieLength(int value) {
      validate(fields()[9], value);
      this.MovieLength = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieLength' field has been set */
    public boolean hasMovieLength() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'MovieLength' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearMovieLength() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'MovieGenre' field */
    public java.lang.CharSequence getMovieGenre() {
      return MovieGenre;
    }
    
    /** Sets the value of the 'MovieGenre' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder setMovieGenre(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.MovieGenre = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'MovieGenre' field has been set */
    public boolean hasMovieGenre() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'MovieGenre' field */
    public com.cloudwick.generator.avro.ODVSRecord.Builder clearMovieGenre() {
      MovieGenre = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    public ODVSRecord build() {
      try {
        ODVSRecord record = new ODVSRecord();
        record.CId = fieldSetFlags()[0] ? this.CId : (java.lang.Integer) defaultValue(fields()[0]);
        record.CName = fieldSetFlags()[1] ? this.CName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.UserActive = fieldSetFlags()[2] ? this.UserActive : (java.lang.Integer) defaultValue(fields()[2]);
        record.TimeStamp = fieldSetFlags()[3] ? this.TimeStamp : (java.lang.Long) defaultValue(fields()[3]);
        record.PauseTime = fieldSetFlags()[4] ? this.PauseTime : (java.lang.Long) defaultValue(fields()[4]);
        record.MovieRating = fieldSetFlags()[5] ? this.MovieRating : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.MovieID = fieldSetFlags()[6] ? this.MovieID : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.MovieName = fieldSetFlags()[7] ? this.MovieName : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.MovieReleaseDate = fieldSetFlags()[8] ? this.MovieReleaseDate : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.MovieLength = fieldSetFlags()[9] ? this.MovieLength : (java.lang.Integer) defaultValue(fields()[9]);
        record.MovieGenre = fieldSetFlags()[10] ? this.MovieGenre : (java.lang.CharSequence) defaultValue(fields()[10]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
