/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.cloudwick.generator.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OSGERecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OSGERecord\",\"namespace\":\"com.cloudwick.generator.avro\",\"fields\":[{\"name\":\"CId\",\"type\":\"string\"},{\"name\":\"CName\",\"type\":\"string\"},{\"name\":\"CEmail\",\"type\":\"string\"},{\"name\":\"CGender\",\"type\":\"string\"},{\"name\":\"CAge\",\"type\":\"int\"},{\"name\":\"CAddress\",\"type\":\"string\"},{\"name\":\"CCountry\",\"type\":\"string\"},{\"name\":\"CRegisterDate\",\"type\":\"long\"},{\"name\":\"CFriendCount\",\"type\":\"int\"},{\"name\":\"CLifeTime\",\"type\":\"int\"},{\"name\":\"CityPlayedCount\",\"type\":\"int\"},{\"name\":\"PictionaryPlayedCount\",\"type\":\"int\"},{\"name\":\"ScramblePlayedCount\",\"type\":\"int\"},{\"name\":\"SniperPlayedCount\",\"type\":\"int\"},{\"name\":\"CRevenue\",\"type\":\"int\"},{\"name\":\"PaidSubscriber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence CId;
  @Deprecated public java.lang.CharSequence CName;
  @Deprecated public java.lang.CharSequence CEmail;
  @Deprecated public java.lang.CharSequence CGender;
  @Deprecated public int CAge;
  @Deprecated public java.lang.CharSequence CAddress;
  @Deprecated public java.lang.CharSequence CCountry;
  @Deprecated public long CRegisterDate;
  @Deprecated public int CFriendCount;
  @Deprecated public int CLifeTime;
  @Deprecated public int CityPlayedCount;
  @Deprecated public int PictionaryPlayedCount;
  @Deprecated public int ScramblePlayedCount;
  @Deprecated public int SniperPlayedCount;
  @Deprecated public int CRevenue;
  @Deprecated public java.lang.CharSequence PaidSubscriber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public OSGERecord() {}

  /**
   * All-args constructor.
   */
  public OSGERecord(java.lang.CharSequence CId, java.lang.CharSequence CName, java.lang.CharSequence CEmail, java.lang.CharSequence CGender, java.lang.Integer CAge, java.lang.CharSequence CAddress, java.lang.CharSequence CCountry, java.lang.Long CRegisterDate, java.lang.Integer CFriendCount, java.lang.Integer CLifeTime, java.lang.Integer CityPlayedCount, java.lang.Integer PictionaryPlayedCount, java.lang.Integer ScramblePlayedCount, java.lang.Integer SniperPlayedCount, java.lang.Integer CRevenue, java.lang.CharSequence PaidSubscriber) {
    this.CId = CId;
    this.CName = CName;
    this.CEmail = CEmail;
    this.CGender = CGender;
    this.CAge = CAge;
    this.CAddress = CAddress;
    this.CCountry = CCountry;
    this.CRegisterDate = CRegisterDate;
    this.CFriendCount = CFriendCount;
    this.CLifeTime = CLifeTime;
    this.CityPlayedCount = CityPlayedCount;
    this.PictionaryPlayedCount = PictionaryPlayedCount;
    this.ScramblePlayedCount = ScramblePlayedCount;
    this.SniperPlayedCount = SniperPlayedCount;
    this.CRevenue = CRevenue;
    this.PaidSubscriber = PaidSubscriber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CId;
    case 1: return CName;
    case 2: return CEmail;
    case 3: return CGender;
    case 4: return CAge;
    case 5: return CAddress;
    case 6: return CCountry;
    case 7: return CRegisterDate;
    case 8: return CFriendCount;
    case 9: return CLifeTime;
    case 10: return CityPlayedCount;
    case 11: return PictionaryPlayedCount;
    case 12: return ScramblePlayedCount;
    case 13: return SniperPlayedCount;
    case 14: return CRevenue;
    case 15: return PaidSubscriber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CId = (java.lang.CharSequence)value$; break;
    case 1: CName = (java.lang.CharSequence)value$; break;
    case 2: CEmail = (java.lang.CharSequence)value$; break;
    case 3: CGender = (java.lang.CharSequence)value$; break;
    case 4: CAge = (java.lang.Integer)value$; break;
    case 5: CAddress = (java.lang.CharSequence)value$; break;
    case 6: CCountry = (java.lang.CharSequence)value$; break;
    case 7: CRegisterDate = (java.lang.Long)value$; break;
    case 8: CFriendCount = (java.lang.Integer)value$; break;
    case 9: CLifeTime = (java.lang.Integer)value$; break;
    case 10: CityPlayedCount = (java.lang.Integer)value$; break;
    case 11: PictionaryPlayedCount = (java.lang.Integer)value$; break;
    case 12: ScramblePlayedCount = (java.lang.Integer)value$; break;
    case 13: SniperPlayedCount = (java.lang.Integer)value$; break;
    case 14: CRevenue = (java.lang.Integer)value$; break;
    case 15: PaidSubscriber = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CId' field.
   */
  public java.lang.CharSequence getCId() {
    return CId;
  }

  /**
   * Sets the value of the 'CId' field.
   * @param value the value to set.
   */
  public void setCId(java.lang.CharSequence value) {
    this.CId = value;
  }

  /**
   * Gets the value of the 'CName' field.
   */
  public java.lang.CharSequence getCName() {
    return CName;
  }

  /**
   * Sets the value of the 'CName' field.
   * @param value the value to set.
   */
  public void setCName(java.lang.CharSequence value) {
    this.CName = value;
  }

  /**
   * Gets the value of the 'CEmail' field.
   */
  public java.lang.CharSequence getCEmail() {
    return CEmail;
  }

  /**
   * Sets the value of the 'CEmail' field.
   * @param value the value to set.
   */
  public void setCEmail(java.lang.CharSequence value) {
    this.CEmail = value;
  }

  /**
   * Gets the value of the 'CGender' field.
   */
  public java.lang.CharSequence getCGender() {
    return CGender;
  }

  /**
   * Sets the value of the 'CGender' field.
   * @param value the value to set.
   */
  public void setCGender(java.lang.CharSequence value) {
    this.CGender = value;
  }

  /**
   * Gets the value of the 'CAge' field.
   */
  public java.lang.Integer getCAge() {
    return CAge;
  }

  /**
   * Sets the value of the 'CAge' field.
   * @param value the value to set.
   */
  public void setCAge(java.lang.Integer value) {
    this.CAge = value;
  }

  /**
   * Gets the value of the 'CAddress' field.
   */
  public java.lang.CharSequence getCAddress() {
    return CAddress;
  }

  /**
   * Sets the value of the 'CAddress' field.
   * @param value the value to set.
   */
  public void setCAddress(java.lang.CharSequence value) {
    this.CAddress = value;
  }

  /**
   * Gets the value of the 'CCountry' field.
   */
  public java.lang.CharSequence getCCountry() {
    return CCountry;
  }

  /**
   * Sets the value of the 'CCountry' field.
   * @param value the value to set.
   */
  public void setCCountry(java.lang.CharSequence value) {
    this.CCountry = value;
  }

  /**
   * Gets the value of the 'CRegisterDate' field.
   */
  public java.lang.Long getCRegisterDate() {
    return CRegisterDate;
  }

  /**
   * Sets the value of the 'CRegisterDate' field.
   * @param value the value to set.
   */
  public void setCRegisterDate(java.lang.Long value) {
    this.CRegisterDate = value;
  }

  /**
   * Gets the value of the 'CFriendCount' field.
   */
  public java.lang.Integer getCFriendCount() {
    return CFriendCount;
  }

  /**
   * Sets the value of the 'CFriendCount' field.
   * @param value the value to set.
   */
  public void setCFriendCount(java.lang.Integer value) {
    this.CFriendCount = value;
  }

  /**
   * Gets the value of the 'CLifeTime' field.
   */
  public java.lang.Integer getCLifeTime() {
    return CLifeTime;
  }

  /**
   * Sets the value of the 'CLifeTime' field.
   * @param value the value to set.
   */
  public void setCLifeTime(java.lang.Integer value) {
    this.CLifeTime = value;
  }

  /**
   * Gets the value of the 'CityPlayedCount' field.
   */
  public java.lang.Integer getCityPlayedCount() {
    return CityPlayedCount;
  }

  /**
   * Sets the value of the 'CityPlayedCount' field.
   * @param value the value to set.
   */
  public void setCityPlayedCount(java.lang.Integer value) {
    this.CityPlayedCount = value;
  }

  /**
   * Gets the value of the 'PictionaryPlayedCount' field.
   */
  public java.lang.Integer getPictionaryPlayedCount() {
    return PictionaryPlayedCount;
  }

  /**
   * Sets the value of the 'PictionaryPlayedCount' field.
   * @param value the value to set.
   */
  public void setPictionaryPlayedCount(java.lang.Integer value) {
    this.PictionaryPlayedCount = value;
  }

  /**
   * Gets the value of the 'ScramblePlayedCount' field.
   */
  public java.lang.Integer getScramblePlayedCount() {
    return ScramblePlayedCount;
  }

  /**
   * Sets the value of the 'ScramblePlayedCount' field.
   * @param value the value to set.
   */
  public void setScramblePlayedCount(java.lang.Integer value) {
    this.ScramblePlayedCount = value;
  }

  /**
   * Gets the value of the 'SniperPlayedCount' field.
   */
  public java.lang.Integer getSniperPlayedCount() {
    return SniperPlayedCount;
  }

  /**
   * Sets the value of the 'SniperPlayedCount' field.
   * @param value the value to set.
   */
  public void setSniperPlayedCount(java.lang.Integer value) {
    this.SniperPlayedCount = value;
  }

  /**
   * Gets the value of the 'CRevenue' field.
   */
  public java.lang.Integer getCRevenue() {
    return CRevenue;
  }

  /**
   * Sets the value of the 'CRevenue' field.
   * @param value the value to set.
   */
  public void setCRevenue(java.lang.Integer value) {
    this.CRevenue = value;
  }

  /**
   * Gets the value of the 'PaidSubscriber' field.
   */
  public java.lang.CharSequence getPaidSubscriber() {
    return PaidSubscriber;
  }

  /**
   * Sets the value of the 'PaidSubscriber' field.
   * @param value the value to set.
   */
  public void setPaidSubscriber(java.lang.CharSequence value) {
    this.PaidSubscriber = value;
  }

  /** Creates a new OSGERecord RecordBuilder */
  public static com.cloudwick.generator.avro.OSGERecord.Builder newBuilder() {
    return new com.cloudwick.generator.avro.OSGERecord.Builder();
  }
  
  /** Creates a new OSGERecord RecordBuilder by copying an existing Builder */
  public static com.cloudwick.generator.avro.OSGERecord.Builder newBuilder(com.cloudwick.generator.avro.OSGERecord.Builder other) {
    return new com.cloudwick.generator.avro.OSGERecord.Builder(other);
  }
  
  /** Creates a new OSGERecord RecordBuilder by copying an existing OSGERecord instance */
  public static com.cloudwick.generator.avro.OSGERecord.Builder newBuilder(com.cloudwick.generator.avro.OSGERecord other) {
    return new com.cloudwick.generator.avro.OSGERecord.Builder(other);
  }
  
  /**
   * RecordBuilder for OSGERecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OSGERecord>
    implements org.apache.avro.data.RecordBuilder<OSGERecord> {

    private java.lang.CharSequence CId;
    private java.lang.CharSequence CName;
    private java.lang.CharSequence CEmail;
    private java.lang.CharSequence CGender;
    private int CAge;
    private java.lang.CharSequence CAddress;
    private java.lang.CharSequence CCountry;
    private long CRegisterDate;
    private int CFriendCount;
    private int CLifeTime;
    private int CityPlayedCount;
    private int PictionaryPlayedCount;
    private int ScramblePlayedCount;
    private int SniperPlayedCount;
    private int CRevenue;
    private java.lang.CharSequence PaidSubscriber;

    /** Creates a new Builder */
    private Builder() {
      super(com.cloudwick.generator.avro.OSGERecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.cloudwick.generator.avro.OSGERecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CName)) {
        this.CName = data().deepCopy(fields()[1].schema(), other.CName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CEmail)) {
        this.CEmail = data().deepCopy(fields()[2].schema(), other.CEmail);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CGender)) {
        this.CGender = data().deepCopy(fields()[3].schema(), other.CGender);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CAge)) {
        this.CAge = data().deepCopy(fields()[4].schema(), other.CAge);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CAddress)) {
        this.CAddress = data().deepCopy(fields()[5].schema(), other.CAddress);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.CCountry)) {
        this.CCountry = data().deepCopy(fields()[6].schema(), other.CCountry);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.CRegisterDate)) {
        this.CRegisterDate = data().deepCopy(fields()[7].schema(), other.CRegisterDate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.CFriendCount)) {
        this.CFriendCount = data().deepCopy(fields()[8].schema(), other.CFriendCount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.CLifeTime)) {
        this.CLifeTime = data().deepCopy(fields()[9].schema(), other.CLifeTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.CityPlayedCount)) {
        this.CityPlayedCount = data().deepCopy(fields()[10].schema(), other.CityPlayedCount);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.PictionaryPlayedCount)) {
        this.PictionaryPlayedCount = data().deepCopy(fields()[11].schema(), other.PictionaryPlayedCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ScramblePlayedCount)) {
        this.ScramblePlayedCount = data().deepCopy(fields()[12].schema(), other.ScramblePlayedCount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.SniperPlayedCount)) {
        this.SniperPlayedCount = data().deepCopy(fields()[13].schema(), other.SniperPlayedCount);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CRevenue)) {
        this.CRevenue = data().deepCopy(fields()[14].schema(), other.CRevenue);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.PaidSubscriber)) {
        this.PaidSubscriber = data().deepCopy(fields()[15].schema(), other.PaidSubscriber);
        fieldSetFlags()[15] = true;
      }
    }
    
    /** Creates a Builder by copying an existing OSGERecord instance */
    private Builder(com.cloudwick.generator.avro.OSGERecord other) {
            super(com.cloudwick.generator.avro.OSGERecord.SCHEMA$);
      if (isValidValue(fields()[0], other.CId)) {
        this.CId = data().deepCopy(fields()[0].schema(), other.CId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CName)) {
        this.CName = data().deepCopy(fields()[1].schema(), other.CName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.CEmail)) {
        this.CEmail = data().deepCopy(fields()[2].schema(), other.CEmail);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CGender)) {
        this.CGender = data().deepCopy(fields()[3].schema(), other.CGender);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CAge)) {
        this.CAge = data().deepCopy(fields()[4].schema(), other.CAge);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.CAddress)) {
        this.CAddress = data().deepCopy(fields()[5].schema(), other.CAddress);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.CCountry)) {
        this.CCountry = data().deepCopy(fields()[6].schema(), other.CCountry);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.CRegisterDate)) {
        this.CRegisterDate = data().deepCopy(fields()[7].schema(), other.CRegisterDate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.CFriendCount)) {
        this.CFriendCount = data().deepCopy(fields()[8].schema(), other.CFriendCount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.CLifeTime)) {
        this.CLifeTime = data().deepCopy(fields()[9].schema(), other.CLifeTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.CityPlayedCount)) {
        this.CityPlayedCount = data().deepCopy(fields()[10].schema(), other.CityPlayedCount);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.PictionaryPlayedCount)) {
        this.PictionaryPlayedCount = data().deepCopy(fields()[11].schema(), other.PictionaryPlayedCount);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ScramblePlayedCount)) {
        this.ScramblePlayedCount = data().deepCopy(fields()[12].schema(), other.ScramblePlayedCount);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.SniperPlayedCount)) {
        this.SniperPlayedCount = data().deepCopy(fields()[13].schema(), other.SniperPlayedCount);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CRevenue)) {
        this.CRevenue = data().deepCopy(fields()[14].schema(), other.CRevenue);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.PaidSubscriber)) {
        this.PaidSubscriber = data().deepCopy(fields()[15].schema(), other.PaidSubscriber);
        fieldSetFlags()[15] = true;
      }
    }

    /** Gets the value of the 'CId' field */
    public java.lang.CharSequence getCId() {
      return CId;
    }
    
    /** Sets the value of the 'CId' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'CId' field has been set */
    public boolean hasCId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'CId' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCId() {
      CId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'CName' field */
    public java.lang.CharSequence getCName() {
      return CName;
    }
    
    /** Sets the value of the 'CName' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.CName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'CName' field has been set */
    public boolean hasCName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'CName' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCName() {
      CName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'CEmail' field */
    public java.lang.CharSequence getCEmail() {
      return CEmail;
    }
    
    /** Sets the value of the 'CEmail' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.CEmail = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'CEmail' field has been set */
    public boolean hasCEmail() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'CEmail' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCEmail() {
      CEmail = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'CGender' field */
    public java.lang.CharSequence getCGender() {
      return CGender;
    }
    
    /** Sets the value of the 'CGender' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCGender(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.CGender = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'CGender' field has been set */
    public boolean hasCGender() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'CGender' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCGender() {
      CGender = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'CAge' field */
    public java.lang.Integer getCAge() {
      return CAge;
    }
    
    /** Sets the value of the 'CAge' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCAge(int value) {
      validate(fields()[4], value);
      this.CAge = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'CAge' field has been set */
    public boolean hasCAge() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'CAge' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCAge() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'CAddress' field */
    public java.lang.CharSequence getCAddress() {
      return CAddress;
    }
    
    /** Sets the value of the 'CAddress' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCAddress(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.CAddress = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'CAddress' field has been set */
    public boolean hasCAddress() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'CAddress' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCAddress() {
      CAddress = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'CCountry' field */
    public java.lang.CharSequence getCCountry() {
      return CCountry;
    }
    
    /** Sets the value of the 'CCountry' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCCountry(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.CCountry = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'CCountry' field has been set */
    public boolean hasCCountry() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'CCountry' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCCountry() {
      CCountry = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'CRegisterDate' field */
    public java.lang.Long getCRegisterDate() {
      return CRegisterDate;
    }
    
    /** Sets the value of the 'CRegisterDate' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCRegisterDate(long value) {
      validate(fields()[7], value);
      this.CRegisterDate = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'CRegisterDate' field has been set */
    public boolean hasCRegisterDate() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'CRegisterDate' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCRegisterDate() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'CFriendCount' field */
    public java.lang.Integer getCFriendCount() {
      return CFriendCount;
    }
    
    /** Sets the value of the 'CFriendCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCFriendCount(int value) {
      validate(fields()[8], value);
      this.CFriendCount = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'CFriendCount' field has been set */
    public boolean hasCFriendCount() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'CFriendCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCFriendCount() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'CLifeTime' field */
    public java.lang.Integer getCLifeTime() {
      return CLifeTime;
    }
    
    /** Sets the value of the 'CLifeTime' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCLifeTime(int value) {
      validate(fields()[9], value);
      this.CLifeTime = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'CLifeTime' field has been set */
    public boolean hasCLifeTime() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'CLifeTime' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCLifeTime() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'CityPlayedCount' field */
    public java.lang.Integer getCityPlayedCount() {
      return CityPlayedCount;
    }
    
    /** Sets the value of the 'CityPlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCityPlayedCount(int value) {
      validate(fields()[10], value);
      this.CityPlayedCount = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'CityPlayedCount' field has been set */
    public boolean hasCityPlayedCount() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'CityPlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCityPlayedCount() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'PictionaryPlayedCount' field */
    public java.lang.Integer getPictionaryPlayedCount() {
      return PictionaryPlayedCount;
    }
    
    /** Sets the value of the 'PictionaryPlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setPictionaryPlayedCount(int value) {
      validate(fields()[11], value);
      this.PictionaryPlayedCount = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'PictionaryPlayedCount' field has been set */
    public boolean hasPictionaryPlayedCount() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'PictionaryPlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearPictionaryPlayedCount() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'ScramblePlayedCount' field */
    public java.lang.Integer getScramblePlayedCount() {
      return ScramblePlayedCount;
    }
    
    /** Sets the value of the 'ScramblePlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setScramblePlayedCount(int value) {
      validate(fields()[12], value);
      this.ScramblePlayedCount = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'ScramblePlayedCount' field has been set */
    public boolean hasScramblePlayedCount() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'ScramblePlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearScramblePlayedCount() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'SniperPlayedCount' field */
    public java.lang.Integer getSniperPlayedCount() {
      return SniperPlayedCount;
    }
    
    /** Sets the value of the 'SniperPlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setSniperPlayedCount(int value) {
      validate(fields()[13], value);
      this.SniperPlayedCount = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'SniperPlayedCount' field has been set */
    public boolean hasSniperPlayedCount() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'SniperPlayedCount' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearSniperPlayedCount() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'CRevenue' field */
    public java.lang.Integer getCRevenue() {
      return CRevenue;
    }
    
    /** Sets the value of the 'CRevenue' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setCRevenue(int value) {
      validate(fields()[14], value);
      this.CRevenue = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'CRevenue' field has been set */
    public boolean hasCRevenue() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'CRevenue' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearCRevenue() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'PaidSubscriber' field */
    public java.lang.CharSequence getPaidSubscriber() {
      return PaidSubscriber;
    }
    
    /** Sets the value of the 'PaidSubscriber' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder setPaidSubscriber(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.PaidSubscriber = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'PaidSubscriber' field has been set */
    public boolean hasPaidSubscriber() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'PaidSubscriber' field */
    public com.cloudwick.generator.avro.OSGERecord.Builder clearPaidSubscriber() {
      PaidSubscriber = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    public OSGERecord build() {
      try {
        OSGERecord record = new OSGERecord();
        record.CId = fieldSetFlags()[0] ? this.CId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.CName = fieldSetFlags()[1] ? this.CName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.CEmail = fieldSetFlags()[2] ? this.CEmail : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CGender = fieldSetFlags()[3] ? this.CGender : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.CAge = fieldSetFlags()[4] ? this.CAge : (java.lang.Integer) defaultValue(fields()[4]);
        record.CAddress = fieldSetFlags()[5] ? this.CAddress : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.CCountry = fieldSetFlags()[6] ? this.CCountry : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.CRegisterDate = fieldSetFlags()[7] ? this.CRegisterDate : (java.lang.Long) defaultValue(fields()[7]);
        record.CFriendCount = fieldSetFlags()[8] ? this.CFriendCount : (java.lang.Integer) defaultValue(fields()[8]);
        record.CLifeTime = fieldSetFlags()[9] ? this.CLifeTime : (java.lang.Integer) defaultValue(fields()[9]);
        record.CityPlayedCount = fieldSetFlags()[10] ? this.CityPlayedCount : (java.lang.Integer) defaultValue(fields()[10]);
        record.PictionaryPlayedCount = fieldSetFlags()[11] ? this.PictionaryPlayedCount : (java.lang.Integer) defaultValue(fields()[11]);
        record.ScramblePlayedCount = fieldSetFlags()[12] ? this.ScramblePlayedCount : (java.lang.Integer) defaultValue(fields()[12]);
        record.SniperPlayedCount = fieldSetFlags()[13] ? this.SniperPlayedCount : (java.lang.Integer) defaultValue(fields()[13]);
        record.CRevenue = fieldSetFlags()[14] ? this.CRevenue : (java.lang.Integer) defaultValue(fields()[14]);
        record.PaidSubscriber = fieldSetFlags()[15] ? this.PaidSubscriber : (java.lang.CharSequence) defaultValue(fields()[15]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
